spring.application.name=api-gateway

# API Gateway chạy port 9000 (8080/8081/8082 đã được các service dùng)
server.port=9000

# URL các service đích (đổi theo môi trường, không cần sửa code)
services.product.url=http://localhost:8080
services.order.url=http://localhost:8081
services.inventory.url=http://localhost:8082
